-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."patientDB"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    card_id integer NOT NULL,
    patient_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    patient_lastname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "patientDB_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."cardDB"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default" NOT NULL,
    phonenumber text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "cardDB_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."appointmentDB"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    data timestamp without time zone NOT NULL,
    CONSTRAINT "appointmentDB_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."doctorDB"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "position" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "doctorDB_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."patientDB"
    ADD CONSTRAINT card_id FOREIGN KEY (card_id)
    REFERENCES public."cardDB" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."appointmentDB"
    ADD CONSTRAINT doctoe_id FOREIGN KEY (doctor_id)
    REFERENCES public."doctorDB" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."appointmentDB"
    ADD CONSTRAINT patient_id FOREIGN KEY (patient_id)
    REFERENCES public."patientDB" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;