-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."customerDB"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lastame character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "car brand" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "car number" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "customerDB_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."repairDB"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    customer_id integer NOT NULL,
    master_id integer NOT NULL,
    report text COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    CONSTRAINT "repairDB_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."mastersDB"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "mastersDB_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."sparesDB"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    serial_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL DEFAULT 0,
    CONSTRAINT "sparesDB_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."repairDB"
    ADD CONSTRAINT customer_id FOREIGN KEY (customer_id)
    REFERENCES public."customerDB" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."repairDB"
    ADD CONSTRAINT master_id FOREIGN KEY (master_id)
    REFERENCES public."mastersDB" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;